on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Navigate to App Directory
        run: |
          cd /home/matt/Documents/repos/smart-home_dashboard
          
      - name: Pull Latest Code
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git pull https://$GITHUB_TOKEN@github.com/m-ray-ofSunshine/smart-home_dashboard.git main

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build

      - name: Clean up Docker images
        run: docker image prune -af
