on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build

      - name: Clean up Docker images
        run: docker image prune -af
